// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSWaterMark
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSWaterMark.ba592631-4321-4937-83fa-cfe42d40f0c8";
        public const string Name = "WaterMark";
        public const string Description = @"Add a configurable watermark to the editor.";
        public const string Language = "en-US";
        public const string Version = "1.8.2";
        public const string Author = "Matt Lacey";
        public const string Tags = "";
    }
}
